name: DNS Czechia Test CI

on:
  push:
    branches: [ "master", "dev" ]
  workflow_dispatch: 

jobs:
  test-plugin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Syntax check
      run: bash -n dnsapi/dns_czechia.sh

    - name: Run ONLY Czechia DNS Test
      env:
        # Tvoje credentials
        TokenName1: ${{ secrets.CZ_TOKEN }}
        TokenName2: ${{ secrets.CZ_ZONES }}
        # Nastavení pro acme.sh
        TEST_DNS: dns_czechia
        TEST_DNS_SLEEP: 120
      run: |
        # 1. Nainstalujeme acme.sh přímo sem do runneru
        curl https://get.acme.sh | sh -s email=test@example.com
        
        # 2. Zkopírujeme tvůj nový DNS plugin tam, kam patří
        cp dnsapi/dns_czechia.sh ~/.acme.sh/dnsapi/
        chmod +x ~/.acme.sh/dnsapi/dns_czechia.sh
        
        # 3. Pustíme ostrý test proti Let's Encrypt staging serveru (ať nespálíme limity)
        # Použijeme tvou doménu z CZ_ZONES
        ~/.acme.sh/acme.sh --issue --dns dns_czechia \
          -d "$TokenName2" \
          --server letsencrypt --staging \
          --debug 2
